# Generated by Django 2.1.1 on 2018-09-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(help_text='Id da Steam', primary_key=True, serialize=False, verbose_name='Stream ID')),
                ('name', models.CharField(help_text='Name of game', max_length=100, null=True, verbose_name='Name')),
                ('game_evaluation_chart', models.CharField(help_text='Game evaluation chart', max_length=100, null=True, verbose_name='Game evaluation chart')),
                ('Rating_reviews', models.CharField(help_text='umber of Like or dislike in the game', max_length=100, null=True, verbose_name='Like or dislike in the game')),
                ('negative_reviews_steam', models.IntegerField(help_text='Number of negatives reviews in the game', null=True, verbose_name='Negatives reviews')),
            ],
        ),
    ]
