# Generated by Django 2.1.1 on 2018-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSearch',
            fields=[
                ('id', models.CharField(help_text='Video ID', max_length=100, primary_key=True, serialize=False, verbose_name='Video ID')),
                ('name', models.CharField(help_text='Name of the game', max_length=100, null=True, verbose_name='Name')),
                ('count_views', models.IntegerField(help_text='Numbers of video views', null=True, verbose_name='count_views')),
                ('count_likes', models.IntegerField(help_text='Number of likes', null=True, verbose_name='count_likes')),
                ('count_dislikes', models.IntegerField(help_text='Number of dislikes', null=True, verbose_name='count_dislikes')),
                ('count_comments', models.IntegerField(help_text='Number of comment', null=True, verbose_name='count_comment')),
                ('regionCode', models.CharField(max_length=10, null=True, verbose_name='Region Code')),
            ],
        ),
    ]
