# Generated by Django 2.1.1 on 2018-09-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubesearch',
            name='count_comments',
        ),
        migrations.RemoveField(
            model_name='youtubesearch',
            name='count_dislikes',
        ),
        migrations.RemoveField(
            model_name='youtubesearch',
            name='count_likes',
        ),
        migrations.RemoveField(
            model_name='youtubesearch',
            name='count_views',
        ),
        migrations.RemoveField(
            model_name='youtubesearch',
            name='name',
        ),
        migrations.AlterField(
            model_name='youtubesearch',
            name='regionCode',
            field=models.CharField(max_length=10, null=True, verbose_name='regionCode'),
        ),
    ]
