# Generated by Django 2.1.1 on 2018-09-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0002_auto_20180911_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubesearch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
